export interface Recipe {
  id: string;
  title: string;
  subtitle: string;
  cookTime: number;
  servings: number;
  difficulty: "Easy" | "Medium";
  ingredients: string[];
  steps: string[];
  category: string;
  tags: string[];
}

export const CATEGORIES = [
  "All",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Snack",
  "Dessert",
];

export const COMMON_INGREDIENTS = [
  "Eggs",
  "Milk",
  "Butter",
  "Cheese",
  "Bread",
  "Rice",
  "Pasta",
  "Chicken",
  "Ground Beef",
  "Onion",
  "Garlic",
  "Tomato",
  "Potato",
  "Carrot",
  "Bell Pepper",
  "Lettuce",
  "Avocado",
  "Lemon",
  "Olive Oil",
  "Salt",
  "Pepper",
  "Flour",
  "Sugar",
  "Honey",
  "Soy Sauce",
  "Tortilla",
  "Beans",
  "Spinach",
  "Mushroom",
  "Bacon",
  "Ham",
  "Tuna",
  "Yogurt",
  "Cream Cheese",
  "Peanut Butter",
  "Banana",
  "Apple",
  "Oats",
  "Broccoli",
  "Corn",
];

export const RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Classic Scrambled Eggs",
    subtitle: "Creamy and fluffy in 5 minutes",
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Eggs", "Butter", "Salt", "Pepper", "Milk"],
    steps: [
      "Crack 4 eggs into a bowl and whisk with a splash of milk, salt, and pepper.",
      "Melt butter in a non-stick pan over medium-low heat.",
      "Pour in the egg mixture and gently stir with a spatula.",
      "Keep folding until eggs are just set but still slightly wet.",
      "Remove from heat immediately and serve.",
    ],
    category: "Breakfast",
    tags: ["quick", "protein"],
  },
  {
    id: "2",
    title: "Garlic Butter Pasta",
    subtitle: "A pantry staple classic",
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    ingredients: ["Pasta", "Garlic", "Butter", "Olive Oil", "Salt", "Pepper"],
    steps: [
      "Cook pasta according to package directions, reserve 1 cup pasta water.",
      "Slice 4 cloves of garlic thinly.",
      "In a large pan, melt butter with olive oil over medium heat.",
      "Add garlic and cook until golden, about 2 minutes.",
      "Toss in drained pasta with a splash of pasta water.",
      "Season with salt and pepper, toss until coated.",
    ],
    category: "Dinner",
    tags: ["comfort", "quick"],
  },
  {
    id: "3",
    title: "Avocado Toast",
    subtitle: "Elevated with simple toppings",
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["Bread", "Avocado", "Lemon", "Salt", "Pepper", "Olive Oil"],
    steps: [
      "Toast bread until golden and crispy.",
      "Mash avocado with a squeeze of lemon juice.",
      "Spread avocado generously on toast.",
      "Drizzle with olive oil, season with salt and pepper.",
    ],
    category: "Breakfast",
    tags: ["quick", "healthy"],
  },
  {
    id: "4",
    title: "Chicken Stir Fry",
    subtitle: "Colorful and packed with flavor",
    cookTime: 20,
    servings: 3,
    difficulty: "Easy",
    ingredients: [
      "Chicken",
      "Bell Pepper",
      "Onion",
      "Garlic",
      "Soy Sauce",
      "Rice",
      "Olive Oil",
    ],
    steps: [
      "Cut chicken into bite-sized pieces, season with salt.",
      "Cook rice according to package directions.",
      "Heat oil in a wok or large pan over high heat.",
      "Cook chicken until golden, about 5 minutes. Remove.",
      "Stir fry sliced onion, bell pepper, and garlic for 3 minutes.",
      "Return chicken, add soy sauce, toss everything together.",
      "Serve over hot rice.",
    ],
    category: "Dinner",
    tags: ["protein", "healthy"],
  },
  {
    id: "5",
    title: "Banana Oat Pancakes",
    subtitle: "Naturally sweet and filling",
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Banana", "Oats", "Eggs", "Honey", "Butter"],
    steps: [
      "Mash 2 ripe bananas in a bowl.",
      "Mix in 1 cup oats and 2 eggs until combined.",
      "Heat butter in a pan over medium heat.",
      "Pour small circles of batter, cook 2-3 minutes per side.",
      "Drizzle with honey and serve.",
    ],
    category: "Breakfast",
    tags: ["healthy", "sweet"],
  },
  {
    id: "6",
    title: "Quick Bean Quesadilla",
    subtitle: "Crispy, cheesy, done in minutes",
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Tortilla", "Beans", "Cheese", "Bell Pepper", "Olive Oil"],
    steps: [
      "Mash beans lightly with a fork.",
      "Dice bell pepper finely.",
      "Spread beans on half a tortilla, top with cheese and pepper.",
      "Fold tortilla in half.",
      "Cook in an oiled pan 3 minutes per side until golden.",
      "Cut into wedges and serve.",
    ],
    category: "Lunch",
    tags: ["quick", "comfort"],
  },
  {
    id: "7",
    title: "Creamy Tomato Soup",
    subtitle: "Cozy comfort in a bowl",
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Tomato",
      "Onion",
      "Garlic",
      "Butter",
      "Cream Cheese",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Dice onion and mince garlic.",
      "Melt butter in a pot, cook onion until soft.",
      "Add garlic, cook 1 minute.",
      "Add chopped tomatoes and 2 cups water, simmer 15 minutes.",
      "Blend until smooth, stir in cream cheese.",
      "Season with salt and pepper, serve warm.",
    ],
    category: "Lunch",
    tags: ["comfort", "warm"],
  },
  {
    id: "8",
    title: "Egg Fried Rice",
    subtitle: "Better than takeout",
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "Rice",
      "Eggs",
      "Soy Sauce",
      "Garlic",
      "Onion",
      "Carrot",
      "Olive Oil",
    ],
    steps: [
      "Use day-old rice or cook and spread to cool.",
      "Dice carrot and onion, mince garlic.",
      "Scramble eggs in a hot oiled wok, remove.",
      "Stir fry vegetables until tender, 3 minutes.",
      "Add rice, toss on high heat for 2 minutes.",
      "Add soy sauce, return eggs, mix well.",
    ],
    category: "Dinner",
    tags: ["quick", "comfort"],
  },
  {
    id: "9",
    title: "Peanut Butter Banana Wrap",
    subtitle: "The ultimate quick snack",
    cookTime: 3,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["Tortilla", "Peanut Butter", "Banana", "Honey"],
    steps: [
      "Spread peanut butter on a tortilla.",
      "Slice banana and lay across the center.",
      "Drizzle with honey.",
      "Roll up tightly and slice in half.",
    ],
    category: "Snack",
    tags: ["quick", "sweet", "healthy"],
  },
  {
    id: "10",
    title: "Loaded Baked Potato",
    subtitle: "Simple and satisfying",
    cookTime: 25,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "Potato",
      "Cheese",
      "Butter",
      "Bacon",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Prick potatoes with a fork, microwave 8-10 minutes until tender.",
      "Cook bacon until crispy, crumble.",
      "Cut potatoes open, fluff insides with a fork.",
      "Add butter, season with salt and pepper.",
      "Top with cheese and crumbled bacon.",
    ],
    category: "Dinner",
    tags: ["comfort", "protein"],
  },
  {
    id: "11",
    title: "Greek Yogurt Parfait",
    subtitle: "Layered morning freshness",
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    ingredients: ["Yogurt", "Honey", "Banana", "Oats"],
    steps: [
      "Layer yogurt in the bottom of a glass or bowl.",
      "Add sliced banana and a sprinkle of oats.",
      "Repeat layers.",
      "Drizzle honey on top and serve.",
    ],
    category: "Breakfast",
    tags: ["healthy", "quick"],
  },
  {
    id: "12",
    title: "Spinach Mushroom Omelette",
    subtitle: "Packed with greens",
    cookTime: 10,
    servings: 1,
    difficulty: "Easy",
    ingredients: [
      "Eggs",
      "Spinach",
      "Mushroom",
      "Cheese",
      "Butter",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Whisk 3 eggs with salt and pepper.",
      "Saut\u00e9 sliced mushrooms in butter until golden.",
      "Add spinach, cook until wilted.",
      "Pour eggs over vegetables, cook until edges set.",
      "Add cheese, fold in half, cook 1 more minute.",
    ],
    category: "Breakfast",
    tags: ["protein", "healthy"],
  },
  {
    id: "13",
    title: "Tuna Melt",
    subtitle: "Warm, melty, classic",
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Tuna", "Bread", "Cheese", "Butter", "Onion", "Lemon"],
    steps: [
      "Mix tuna with finely diced onion and a squeeze of lemon.",
      "Butter bread slices on one side.",
      "Place tuna mixture on unbuttered side, top with cheese.",
      "Close sandwich, butter side out.",
      "Cook in a pan 3 minutes per side until golden and melty.",
    ],
    category: "Lunch",
    tags: ["protein", "comfort"],
  },
  {
    id: "14",
    title: "Honey Garlic Chicken",
    subtitle: "Sweet and savory glaze",
    cookTime: 25,
    servings: 3,
    difficulty: "Medium",
    ingredients: [
      "Chicken",
      "Honey",
      "Garlic",
      "Soy Sauce",
      "Butter",
      "Salt",
      "Pepper",
    ],
    steps: [
      "Season chicken pieces with salt and pepper.",
      "Cook chicken in a hot pan with oil until golden, 5 minutes per side.",
      "Mix honey, minced garlic, and soy sauce in a bowl.",
      "Pour sauce over chicken, reduce heat to medium-low.",
      "Simmer 5 minutes, spooning sauce over chicken.",
      "Serve with rice or vegetables.",
    ],
    category: "Dinner",
    tags: ["protein", "sweet"],
  },
  {
    id: "15",
    title: "Apple Peanut Butter Bites",
    subtitle: "Crunchy and satisfying",
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Apple", "Peanut Butter", "Honey", "Oats"],
    steps: [
      "Core and slice apple into thick rounds.",
      "Spread peanut butter on each slice.",
      "Sprinkle with oats.",
      "Drizzle with honey and serve.",
    ],
    category: "Snack",
    tags: ["healthy", "quick"],
  },
  {
    id: "16",
    title: "Cheesy Broccoli Rice",
    subtitle: "One pot family favorite",
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Rice",
      "Broccoli",
      "Cheese",
      "Butter",
      "Garlic",
      "Salt",
      "Pepper",
      "Milk",
    ],
    steps: [
      "Cook rice according to package directions.",
      "Steam broccoli florets until tender, 5 minutes.",
      "In a pot, melt butter, add garlic, cook 1 minute.",
      "Add milk and cheese, stir until melted and smooth.",
      "Fold in rice and broccoli.",
      "Season with salt and pepper, serve warm.",
    ],
    category: "Dinner",
    tags: ["comfort", "family"],
  },
  {
    id: "17",
    title: "Ham & Cheese Roll-Ups",
    subtitle: "Lunchbox ready",
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: ["Ham", "Cheese", "Tortilla", "Lettuce"],
    steps: [
      "Lay a tortilla flat.",
      "Layer ham, cheese, and lettuce.",
      "Roll up tightly.",
      "Cut in half diagonally and serve.",
    ],
    category: "Lunch",
    tags: ["quick", "protein"],
  },
  {
    id: "18",
    title: "Corn & Potato Hash",
    subtitle: "Hearty morning skillet",
    cookTime: 20,
    servings: 3,
    difficulty: "Easy",
    ingredients: [
      "Potato",
      "Corn",
      "Onion",
      "Butter",
      "Salt",
      "Pepper",
      "Eggs",
    ],
    steps: [
      "Dice potatoes into small cubes.",
      "Cook in butter over medium heat until golden, 12 minutes.",
      "Add diced onion and corn, cook 5 minutes.",
      "Season with salt and pepper.",
      "Make small wells, crack eggs in, cover and cook until set.",
    ],
    category: "Breakfast",
    tags: ["hearty", "family"],
  },
];

export function getMatchingRecipes(
  pantryIngredients: string[],
  category?: string,
): (Recipe & { matchCount: number; matchPercent: number })[] {
  const normalizedPantry = pantryIngredients.map((i) => i.toLowerCase());

  return RECIPES.filter((r) => (category && category !== "All" ? r.category === category : true))
    .map((recipe) => {
      const matchCount = recipe.ingredients.filter((ing) =>
        normalizedPantry.includes(ing.toLowerCase()),
      ).length;
      const matchPercent = Math.round(
        (matchCount / recipe.ingredients.length) * 100,
      );
      return { ...recipe, matchCount, matchPercent };
    })
    .sort((a, b) => b.matchPercent - a.matchPercent);
}
